package main;

import javax.swing.*;

import java.time.DayOfWeek;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
public class CalendarView extends JFrame {

    LocalDate today = LocalDate.now();
    LocalDate weekStart;
    List<Task> TasksInDay1 = new ArrayList<Task>();
    LocalDate day2;
    List<Task> TasksInDay2 = new ArrayList<Task>();
    LocalDate day3;
    List<Task> TasksInDay3 = new ArrayList<Task>();
    LocalDate day4;
    List<Task> TasksInDay4 = new ArrayList<Task>();
    LocalDate day5;
    List<Task> TasksInDay5 = new ArrayList<Task>();
    LocalDate day6;
    List<Task> TasksInDay6 = new ArrayList<Task>();
    LocalDate weekEnd;
    List<Task> TasksInDay7 = new ArrayList<Task>();

    int weekIterate = 0;

    JLabel emptyDay = new JLabel();

    TaskController controller;
    /**
     * Creates new form CalendarView
     */
    public CalendarView(TaskController controller) {
        initComponents();
        this.controller = controller;
        FnCalendarSetup();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnNextWeek = new JButton();
        BtnPreviousWeek = new JButton();
        LblWeekPosition = new JLabel();
        jScrollPane1 = new JScrollPane();
        ListDay1 = new JList<>();
        jScrollPane2 = new JScrollPane();
        ListDay2 = new JList<>();
        jScrollPane3 = new JScrollPane();
        ListDay3 = new JList<>();
        jScrollPane4 = new JScrollPane();
        ListDay4 = new JList<>();
        jScrollPane5 = new JScrollPane();
        ListDay5 = new JList<>();
        jScrollPane6 = new JScrollPane();
        ListDay6 = new JList<>();
        jScrollPane7 = new JScrollPane();
        ListDay7 = new JList<>();
        LblDay1 = new JLabel();
        LblDay2 = new JLabel();
        LblDay3 = new JLabel();
        LblDay4 = new JLabel();
        LblDay5 = new JLabel();
        LblDay6 = new JLabel();
        LblDay7 = new JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 500));
        setPreferredSize(new java.awt.Dimension(900, 550));
        setSize(new java.awt.Dimension(900, 550));
        getContentPane().setLayout(null);

        BtnNextWeek.setText("Next Week >>");
        BtnNextWeek.setName("BtnNextWeek"); // NOI18N
        getContentPane().add(BtnNextWeek);
        BtnNextWeek.setBounds(525, 18, 103, 28);

        BtnPreviousWeek.setText("<< Previous Week");
        BtnPreviousWeek.setName("BtnPreviousWeek"); // NOI18N
        getContentPane().add(BtnPreviousWeek);
        BtnPreviousWeek.setBounds(248, 18, 127, 28);

        LblWeekPosition.setText("jLabel1");
        LblWeekPosition.setName("LblWeek"); // NOI18N
        LblWeekPosition.setPreferredSize(new java.awt.Dimension(50, 16));
        getContentPane().add(LblWeekPosition);
        LblWeekPosition.setBounds(425, 24, 50, 16);

        ListDay1.setBorder(BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ListDay1.setModel(new AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ListDay1.setPreferredSize(new java.awt.Dimension(50, 102));
        jScrollPane1.setViewportView(ListDay1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(750, 80, 120, 410);

        ListDay2.setBorder(BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ListDay2.setModel(new AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ListDay2.setPreferredSize(new java.awt.Dimension(50, 102));
        jScrollPane2.setViewportView(ListDay2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(30, 80, 120, 410);

        ListDay3.setBorder(BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ListDay3.setModel(new AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ListDay3.setPreferredSize(new java.awt.Dimension(50, 102));
        jScrollPane3.setViewportView(ListDay3);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(150, 80, 120, 410);

        ListDay4.setBorder(BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ListDay4.setModel(new AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(ListDay4);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(270, 80, 120, 410);

        ListDay5.setBorder(BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ListDay5.setModel(new AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ListDay5.setPreferredSize(new java.awt.Dimension(50, 102));
        jScrollPane5.setViewportView(ListDay5);

        getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(390, 80, 120, 410);

        ListDay6.setBorder(BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ListDay6.setModel(new AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ListDay6.setPreferredSize(new java.awt.Dimension(50, 102));
        jScrollPane6.setViewportView(ListDay6);

        getContentPane().add(jScrollPane6);
        jScrollPane6.setBounds(510, 80, 120, 410);

        ListDay7.setBorder(BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ListDay7.setModel(new AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ListDay7.setPreferredSize(new java.awt.Dimension(50, 102));
        jScrollPane7.setViewportView(ListDay7);

        getContentPane().add(jScrollPane7);
        jScrollPane7.setBounds(630, 80, 120, 410);

        LblDay1.setText("jLabel2");
        getContentPane().add(LblDay1);
        LblDay1.setBounds(70, 60, 41, 16);

        LblDay2.setText("jLabel3");
        getContentPane().add(LblDay2);
        LblDay2.setBounds(190, 60, 41, 16);

        LblDay3.setText("jLabel4");
        getContentPane().add(LblDay3);
        LblDay3.setBounds(310, 60, 41, 16);

        LblDay4.setText("jLabel5");
        getContentPane().add(LblDay4);
        LblDay4.setBounds(425, 60, 41, 16);

        LblDay5.setText("jLabel6");
        getContentPane().add(LblDay5);
        LblDay5.setBounds(540, 60, 41, 16);

        LblDay6.setText("jLabel7");
        getContentPane().add(LblDay6);
        LblDay6.setBounds(670, 60, 41, 16);

        LblDay7.setText("jLabel8");
        getContentPane().add(LblDay7);
        LblDay7.setBounds(790, 60, 41, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FnCalendarSetup(){
        DayOfWeek todayAsDay = today.getDayOfWeek();
        emptyDay.setText("No Tasks Today");

        switch(todayAsDay){
            case SATURDAY:
                weekStart = today.minusDays(6);
                break;
            case SUNDAY:
                weekStart = today;
                break;
            case MONDAY:
                weekStart = today.minusDays(1);
                break;
            case TUESDAY:
                weekStart = today.minusDays(2);
                break;
            case WEDNESDAY:
                weekStart = today.minusDays(3);
                break;
            case THURSDAY:
                weekStart = today.minusDays(4);
                break;
            case FRIDAY: 
                weekStart = today.minusDays(5);
                break;
            default:
                break;
        }

        day2 = weekStart.plusDays(1);
        day3 = weekStart.plusDays(2);
        day4 = weekStart.plusDays(3);
        day5 = weekStart.plusDays(4);
        day6 = weekStart.plusDays(5);
        weekEnd = weekStart.plusDays(6);

        LblDay1.setText(weekStart.toString());
        LblDay2.setText(day2.toString());
        LblDay3.setText(day3.toString());
        LblDay4.setText(day4.toString());
        LblDay5.setText(day5.toString());
        LblDay6.setText(day6.toString());
        LblDay7.setText(weekEnd.toString());

        List<Task> weekTasks = controller.FindTasksBetweenDates(weekStart, weekEnd);

        for (Task task : weekTasks) {
            JLabel tmpLbl = new JLabel();
            tmpLbl.setText(task.getTaskName());
            if(task.getDate() == weekStart){
                ListDay1.add(tmpLbl);
                TasksInDay1.add(task);
            }
            else if(task.getDate() == day2){
                ListDay2.add(tmpLbl);
                TasksInDay2.add(task);
            }
            else if(task.getDate() == day3){
                ListDay3.add(tmpLbl);
                TasksInDay3.add(task);
            }
            else if(task.getDate() == day4){
                ListDay4.add(tmpLbl);
                TasksInDay4.add(task);
            }
            else if(task.getDate() == day5){
                ListDay5.add(tmpLbl);
                TasksInDay5.add(task);
            }
            else if(task.getDate() == day6){
                ListDay6.add(tmpLbl);
                TasksInDay6.add(task);
            }
            if(task.getDate() == weekEnd){
                ListDay7.add(tmpLbl);
                TasksInDay7.add(task);
            }
        }

        if(TasksInDay1.isEmpty()){
            ListDay1.add(emptyDay);
        }
        if(TasksInDay2.isEmpty()){
            ListDay1.add(emptyDay);
        }
        if(TasksInDay3.isEmpty()){
            ListDay1.add(emptyDay);
        }
        if(TasksInDay4.isEmpty()){
            ListDay1.add(emptyDay);
        }
        if(TasksInDay5.isEmpty()){
            ListDay1.add(emptyDay);
        }
        if(TasksInDay6.isEmpty()){
            ListDay1.add(emptyDay);
        }
        if(TasksInDay7.isEmpty()){
            ListDay1.add(emptyDay);
        }
    }

    private void FnCalendarIncrement(){

        weekIterate++;

        if(weekIterate == 1){
            
        }

        weekStart = weekStart.plusWeeks(1);
        day2 = weekStart.plusWeeks(1);
        day3 = weekStart.plusWeeks(1);
        day4 = weekStart.plusWeeks(1);
        day5 = weekStart.plusWeeks(1);
        day6 = weekStart.plusWeeks(1);
        weekEnd = weekStart.plusWeeks(1);

        ListDay1.removeAll();
        ListDay2.removeAll();
        ListDay3.removeAll();
        ListDay4.removeAll();
        ListDay5.removeAll();
        ListDay6.removeAll();
        ListDay7.removeAll();

        TasksInDay1.clear();
        TasksInDay2.clear();
        TasksInDay3.clear();
        TasksInDay4.clear();
        TasksInDay5.clear();
        TasksInDay6.clear();
        TasksInDay7.clear();

        LblDay1.setText(weekStart.toString());
        LblDay2.setText(day2.toString());
        LblDay3.setText(day3.toString());
        LblDay4.setText(day4.toString());
        LblDay5.setText(day5.toString());
        LblDay6.setText(day6.toString());
        LblDay7.setText(weekEnd.toString());

        List<Task> weekTasks = controller.FindTasksBetweenDates(weekStart, weekEnd);

        for (Task task : weekTasks) {
            JLabel tmpLbl = new JLabel();
            tmpLbl.setText(task.getTaskName());
            if(task.getDate() == weekStart){
                ListDay1.add(tmpLbl);
                TasksInDay1.add(task);
            }
            else if(task.getDate() == day2){
                ListDay2.add(tmpLbl);
                TasksInDay2.add(task);
            }
            else if(task.getDate() == day3){
                ListDay3.add(tmpLbl);
                TasksInDay3.add(task);
            }
            else if(task.getDate() == day4){
                ListDay4.add(tmpLbl);
                TasksInDay4.add(task);
            }
            else if(task.getDate() == day5){
                ListDay5.add(tmpLbl);
                TasksInDay5.add(task);
            }
            else if(task.getDate() == day6){
                ListDay6.add(tmpLbl);
                TasksInDay6.add(task);
            }
            if(task.getDate() == weekEnd){
                ListDay7.add(tmpLbl);
                TasksInDay7.add(task);
            }
        }

        if(TasksInDay1.isEmpty()){
            ListDay1.add(emptyDay);
        }
        if(TasksInDay2.isEmpty()){
            ListDay1.add(emptyDay);
        }
        if(TasksInDay3.isEmpty()){
            ListDay1.add(emptyDay);
        }
        if(TasksInDay4.isEmpty()){
            ListDay1.add(emptyDay);
        }
        if(TasksInDay5.isEmpty()){
            ListDay1.add(emptyDay);
        }
        if(TasksInDay6.isEmpty()){
            ListDay1.add(emptyDay);
        }
        if(TasksInDay7.isEmpty()){
            ListDay1.add(emptyDay);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton BtnNextWeek;
    private JButton BtnPreviousWeek;
    private JLabel LblWeekPosition;
    private JLabel LblDay1;
    private JLabel LblDay2;
    private JLabel LblDay3;
    private JLabel LblDay4;
    private JLabel LblDay5;
    private JLabel LblDay6;
    private JLabel LblDay7;
    private JList<String> ListDay1;
    private JList<String> ListDay2;
    private JList<String> ListDay3;
    private JList<String> ListDay4;
    private JList<String> ListDay5;
    private JList<String> ListDay6;
    private JList<String> ListDay7;
    private JScrollPane jScrollPane1;
    private JScrollPane jScrollPane2;
    private JScrollPane jScrollPane3;
    private JScrollPane jScrollPane4;
    private JScrollPane jScrollPane5;
    private JScrollPane jScrollPane6;
    private JScrollPane jScrollPane7;
    // End of variables declaration//GEN-END:variables
}
