package main;

/*
 * Copyright (C) 2022 Grant Docherty
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 *
 * BIT707 – Software Engineering 2021-2022
 * Written for the Graduate Diploma in Information Technology at the Open Polytechnic.
 * This is the work of a student and follows the principles of academic integrity set by the Open Polytech
 */

/**
 *
 * @author Grant Docherty - 5032768
 */
public class ListEmptyHeadingPanel extends javax.swing.JPanel {

    /**
     * Creates new form TaskHeadingPanel
     */
    public ListEmptyHeadingPanel() {
        initComponents();
        this.setName("ListEmptyHeadingPanel");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MsgHeading = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder());
        setPreferredSize(new java.awt.Dimension(300, 50));
        setMaximumSize(getPreferredSize());
        setMinimumSize(getPreferredSize());
        setLayout(new java.awt.BorderLayout());

        MsgHeading.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        MsgHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MsgHeading.setText("No Tasks Created\nCreate a task to populate the list");
        MsgHeading.setName("DateHeading"); // NOI18N
        add(MsgHeading, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MsgHeading;
    // End of variables declaration//GEN-END:variables
}
