package main;

import java.awt.event.*;
import java.awt.*;
import javax.swing.*;
import java.util.ArrayList;
import java.util.List;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author user
 */
public class TaskItemPanel extends javax.swing.JPanel{

    int taskId;
    boolean taskOpened = false;
    List<ItemPanelListener> listeners = new ArrayList<ItemPanelListener>();

    public void addListener(ItemPanelListener toAdd){
        listeners.add(toAdd);
    }

    public void notifyEditOpen(){
        for (ItemPanelListener tl :listeners){
            tl.taskEditOpened(taskId);
        }
    }
    public void notifyEditClose(){
        for (ItemPanelListener tl :listeners){
            tl.taskEditClosed();
        }
    }

    /**
     * Creates new form TaskItemPanel
     */
    public TaskItemPanel(Task t) {
        initComponents();
        taskId = t.getId();
        ChkBoxWithTaskName.setText(t.getTaskName());
        if (t.getDate() != null){
            LblTaskDate.setText(t.getDate().toString());
        } else {
            LblTaskDate.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblTaskDate = new JLabel();
        ChkBoxWithTaskName = new JCheckBox();
        BtnEditTask = new JButton();

        setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        setMaximumSize(new Dimension(300, 50));
        setLayout(null);

        LblTaskDate.setText("TaskDate");
        LblTaskDate.setName("TaskDate"); // NOI18N
        add(LblTaskDate);
        LblTaskDate.setBounds(200, 17, 53, 16);

        ChkBoxWithTaskName.setFont(new Font("sansserif", 1, 12)); // NOI18N
        ChkBoxWithTaskName.setText("TaskName");
        ChkBoxWithTaskName.setName("TaskNameAndCheck"); // NOI18N
        ChkBoxWithTaskName.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        add(ChkBoxWithTaskName);
        ChkBoxWithTaskName.setBounds(10, 14, 83, 18);

        BtnEditTask.setIcon(new ImageIcon(getClass().getResource("/main/resources/icons8-double-right-24.png"))); // NOI18N
        BtnEditTask.setBorder(BorderFactory.createEmptyBorder(1, 1, 1, 1));
        BtnEditTask.setPreferredSize(new Dimension(30, 30));
        BtnEditTask.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                BtnEditTaskActionPerformed(evt);
            }
        });
        add(BtnEditTask);
        BtnEditTask.setBounds(270, 10, 30, 30);
    }// </editor-fold>//GEN-END:initComponents

    protected void BtnEditTaskActionPerformed(ActionEvent evt) {
        if(taskOpened){
            BtnEditTask.setIcon(new ImageIcon(getClass().getResource("/main/resources/icons8-double-right-24.png")));
            notifyEditClose();
            BtnEditTask.setBorder(BorderFactory.createEmptyBorder(1, 1, 1, 1));
            taskOpened = false;
        } else {
            BtnEditTask.setIcon(new ImageIcon(getClass().getResource("/main/resources/icons8-double-left-24.png")));
            this.setBorder(BorderFactory.createEmptyBorder());
            notifyEditOpen();
            taskOpened = true;
        }
    }

    private void jCheckBox1ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    public boolean FnGetCheckbox(){
        if(ChkBoxWithTaskName.isSelected()){
            return true;
        }
        return false;
    }

    private int FnGetRelatedTask(){
        return taskId;
    }

    public boolean FnGetTaskOpen(){
        return taskOpened;
    }

    public void FnSetTaskClosed(){
        taskOpened = false;
        BtnEditTask.setIcon(new ImageIcon(getClass().getResource("/main/resources/icons8-double-right-24.png")));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton BtnEditTask;
    private JCheckBox ChkBoxWithTaskName;
    private JLabel LblTaskDate;
    // End of variables declaration//GEN-END:variables

    interface ItemPanelListener {
        void taskEditOpened(int taskId);
        void taskEditClosed();
    }
}
