package main;

import java.awt.event.*;
import java.awt.*;
import javax.swing.*;
import java.util.ArrayList;
import java.util.List;

/*
 * Copyright (C) 2022 Grant Docherty
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 *
 * BIT707 – Software Engineering 2021-2022
 * Written for the Graduate Diploma in Information Technology at the Open Polytechnic.
 * This is the work of a student and follows the principles of academic integrity set by the Open Polytech
 */

 /**
 *
 * @author Grant Docherty - 5032768
 */
public class TaskItemPanel extends javax.swing.JPanel{

    private int taskId;
    private boolean taskOpened = false;
    private List<ItemPanelListener> listeners = new ArrayList<ItemPanelListener>();
    private Color defaultBackground = this.getBackground();

    public void addListener(ItemPanelListener toAdd){
        listeners.add(toAdd);
    }

    public void notifyEditOpen(){
        for (ItemPanelListener tl :listeners){
            tl.taskEditOpened(taskId);
        }
    }
    public void notifyEditClose(){
        for (ItemPanelListener tl :listeners){
            tl.taskEditClosed();
        }
    }

    /**
     * Creates new form TaskItemPanel
     */
    public TaskItemPanel(Task t) {
        initComponents();
        taskId = t.getId();
        ChkBoxWithTaskName.setText(t.getTaskName());
        if (t.getDate() != null){
            LblTaskDate.setText(t.getDate().toString());
        } else {
            LblTaskDate.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblTaskDate = new JLabel();
        ChkBoxWithTaskName = new JCheckBox();
        BtnEditTask = new JButton();

        setBorder(BorderFactory.createEmptyBorder());
        setPreferredSize(new Dimension(300, 50));
        setMaximumSize(getPreferredSize());
        setMinimumSize(getPreferredSize());
        setLayout(null);

        LblTaskDate.setText("TaskDate");
        LblTaskDate.setName("TaskDate"); // NOI18N
        add(LblTaskDate);
        LblTaskDate.setBounds(200, 17, 80, 16);

        ChkBoxWithTaskName.setFont(new Font("sansserif", 1, 12)); // NOI18N
        ChkBoxWithTaskName.setText("TaskName");
        ChkBoxWithTaskName.setName("TaskNameAndCheck"); // NOI18N
        add(ChkBoxWithTaskName);
        ChkBoxWithTaskName.setBounds(10, 14, 200, 18);

        BtnEditTask.setIcon(new ImageIcon(getClass().getResource("/main/resources/icons8-double-right-24.png"))); // NOI18N
        BtnEditTask.setBorder(BorderFactory.createEmptyBorder(1, 1, 1, 1));
        BtnEditTask.setPreferredSize(new Dimension(30, 30));
        BtnEditTask.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                BtnEditTaskActionPerformed(evt);
            }
        });
        add(BtnEditTask);
        BtnEditTask.setBounds(270, 10, 30, 30);
    }// </editor-fold>//GEN-END:initComponents

    protected void BtnEditTaskActionPerformed(ActionEvent evt) {
        if(taskOpened){
            BtnEditTask.setIcon(new ImageIcon(getClass().getResource("/main/resources/icons8-double-right-24.png")));
            setBorder(BorderFactory.createEmptyBorder());
            setBackground(defaultBackground);
            notifyEditClose();
            taskOpened = false;
        } else {
            BtnEditTask.setIcon(new ImageIcon(getClass().getResource("/main/resources/icons8-double-left-24.png")));
            setBorder(BorderFactory.createLoweredBevelBorder());
            setBackground(new Color(200,200,200));
            notifyEditOpen();
            taskOpened = true;
        }
    }

    public boolean FnGetCheckbox(){
        if(ChkBoxWithTaskName.isSelected()){
            return true;
        }
        return false;
    }

    public int FnGetTaskID(){
        return taskId;
    }

    public boolean FnGetTaskOpen(){
        return taskOpened;
    }

    public void FnSetTaskClosed(){
        taskOpened = false;
        setBackground(defaultBackground);
        BtnEditTask.setIcon(new ImageIcon(getClass().getResource("/main/resources/icons8-double-right-24.png")));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton BtnEditTask;
    private JCheckBox ChkBoxWithTaskName;
    private JLabel LblTaskDate;
    // End of variables declaration//GEN-END:variables

    interface ItemPanelListener {
        void taskEditOpened(int taskId);
        void taskEditClosed();
    }
}
